### ISSUE TITLE
Add option to enable proxy protocol RE:#699

### ISSUE THREAD

**Issue by dcherniv** [kubernetes/ingress-gce#1002]
Please refer to #699 
This is desperately needed for feature parity with AWS.

**Comment by nesl247** [comment]
Any update?

**Comment by CapoD** [comment]
Currently, we are using GKE + Istio (automatically installed) and our applications need to know the source IP of a request. 
Since Istio ingress-gateway service is configuring a TCP Load Balancer, we would need to enable the Proxy Protocol on the GCP LB. Unfortunately, this can only be done on creation.
So we would ask you to provide a service annotation that would allow us to set the Proxy Protocol (Version).
[In AWS this can be done](https://kubernetes.io/docs/concepts/cluster-administration/cloud-providers/#load-balancers)

**Comment by rramkumar1** [comment]
@bowei Is this something that can be addressed by the Gateway API? 

/assign @bowei

**Comment by bowei** [comment]
It seems to make more sense as a value for app-protocol, may want to xref on k/k

**Comment by unixfox** [comment]
I'm also interested into this new annotation. I would like to deploy NGINX behind a TCP LB and I need to preserve the original IP address of the clients.

**Comment by gustavovalverde** [comment]
For people trying to preserve the client's Source IP using Nginx, there's no need to use Proxy Protocol, installing with this configuration will do it (use an updated Nginx):

```yaml
  config:
    enable-real-ip: "true"
    use-forwarded-headers: "true"
    proxy-real-ip-cidr: "130.211.0.0/22,35.191.0.0/[L7-LB_EXTERNAL_IP]/32"
```

cc: @unixfox
