### ISSUE TITLE
gcloud container clusters delete is not deleting some resources 

### ISSUE THREAD

**Issue by liza-mae** [kubernetes/ingress-gce#1195]
Hi,

I have tests that use the command ```glcloud container clusters delete``` to cleanup after testing.  I noticed this command is not deleting firewall rules and other resources like the target pools and forwarding rules.  We have a quota on the firewall rules and when those are not deleted we get an error once we have reached quota.  From the documentation these resources should be cleaned up. 

Referenced documentation: https://cloud.google.com/sdk/gcloud/reference/container/clusters/delete 
```
When you delete a cluster, the following resources are deleted:
 - The master resources
 - All of the node instances in the cluster
 - Any Pods that are running on those instances
 - Any firewalls and routes created by Kubernetes Engine at the time of cluster creation
 - Data stored in host hostPath and emptyDir volumes

The following resources are not deleted:
 - External load balancers created by the cluster
 - Persistent disk volumes
```

**Comment by spencerhance** [comment]
Hi @liza-mae.  I think this is expected behavior.  The firewall rules created by the ingress controller are not part of the cluster creation firewall rules and won't be cleaned up by cluster deletion.  Additionally, target proxies and forwarding rules are part of the load balancer resource.  In order to delete those, you need to delete your ingresses and services before deleting the cluster.

**Comment by liza-mae** [comment]
Thanks @spencerhance I deleted my ingresses and services before deleting the cluster and it worked, closing :) thanks !
