### ISSUE TITLE
Docs: Explain ingress v1 pathType

### ISSUE THREAD

**Issue by carlpett** [kubernetes/ingress-gce#1435]
Currently all Ingress examples are using networking.k8s.io/v1beta1. If using v1 instead, the `pathType` attribute is required. There doesn't appear to be any docs anywhere on how the choices are mapped to the underlying url map?
In particular, is _appears_ `Prefix` doesn't work as I'd expect it to? in my testing at least it seems to yield a url map with exact matching.

**Comment by carlpett** [comment]
Actually, after some more testing: How much of v1 is actually reflected to the underlying load balancer? I'd been making changes to `pathType` and `path` (testing combinations of `Prefix` vs `ImplementationSpecific` and `/` vs `/*`). I was a bit confused when I saw `Prefix`/`/` (the, in my opinion, obvious standard configuration?) working while I was sure I had tried it previously. So I copied the resource yaml, removed the existing one, and then recreated. And then it no longer works? Are there some roundtripping issues here?

**Comment by swetharepakula** [comment]
Currently we depend on the K8s docs to explain the `pathType` field. I believe their current documentation uses the V1 Ingress and mentions the accepted values for the [field](https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types).

We don't have documentation specific to the `ingress-gce` repository. But currently only the `ImplementationSpecific` path type is supported by default. We are still in the process of supporting all the v1 features. We did add support for the different path types, which we recently hid behind a [feature gate](https://github.com/kubernetes/ingress-gce/pull/1392) which may be why the `Prefix` type was temporarily working on master. This change also made it so that Ingress that don't use `ImplementationSpecific` would fail. You can enable the other path types by running the controller with the `--enable-ingress-ga-fields` flag.

**Comment by jorams** [comment]
The lack of support seems like an important thing to warn about somewhere.

The GKE regular channel is currently on kubernetes 1.19, the documentation for 1.19 documents these fields as stable, and using v1beta1 triggers warnings about its deprecation. Everything suggests we should be using v1, but something basic like `pathType: Prefix`, `path: /`, which looks like a very reasonable default for a basic configuration, results in a broken ingress.

**Comment by swetharepakula** [comment]
The API itself is stable in Kubernetes, but the GKE Ingress controllers do not yet support the Ingress V1 API. Users can use V1 Ingresses as long as they do not depend on `ingressClassName` or `pathType` features. We have updated [documentation](https://cloud.google.com/kubernetes-engine/docs/how-to/load-balance-ingress) to indicate we only support `ImplementationSpecific`.

We are working on V1 feature support and will have it ready before Kubernetes 1.22 is available when v1beta1 is removed.

**Comment by freehan** [comment]
Public doc updated. Closing for now. Reopen if needed.
