### ISSUE TITLE
Creating Network Endpoint Group (NEG) before creating workload

### ISSUE THREAD

**Issue by AlbertMoser** [kubernetes/ingress-gce#1755]
It seems that NEGs for a service with annotations: _exposed_ports_ are only created once there are pods matching the service, otherwise, we see correct 'neg-status' annotation (matching zones of cluster) but no NEGs.
Only once Service matching PODs are deployed NEGs appear. However (and this is inconsistent) when pods are deleted, NEGs remain (but with 0 endpoints).

**Steps to reproduce:**
1. Create a service with NEG annotation <insert proper NEG annotation here>
2. Check neg-status annotation of service (it should be there)
3. Check that no NEG was created, no NEG creation Event in service is visible
4. Deploy pod(s) matching the service
5. Now  NEGs appear as well as NEG creation events in Service
6. Delete pod(s) (so service has 0/0 pods)
7. Note that NEGs have remained but have 0 endpoints.

**Expected behavior:**
1. Create a service with NEG annotation <insert proper NEG annotation here>
2. Zonal NEGs are created in zones matching cluster nodes (but remain empty, no endpoints)
3. Deploy pod(s) matching the service
4. Endpoints get added to NEGs
5. Delete pod(s)
6. NEGs remain but are empty

**Comment by swetharepakula** [comment]
Hi @AlbertMoser,

Thanks for creating the issue. Can you tell us more of why this behavior is affecting your use case and how creating empty NEGs before workloads help?

Thanks,
Swetha

**Comment by AlbertMoser** [comment]
Hi @swetharepakula 
Thanks for looking into it. 
For us, this is an issue for us since the deployment of load balancers happens before the deployment of workloads. Moreover, both of them are decoupled. Since NEGs are an integral part of the load balancer, it does not work.

**Comment by adaosantos** [comment]
Any update ?

**Comment by swetharepakula** [comment]
Hi, sorry for the delay in response. I think I misunderstood the problem originally. The Neg controller will create a neg as soon as specified by the service regardless of whether workloads exist or not (matches with the expected behavior).

I am unable to reproduce this issue. In my test setup I create a service specifying a NEG, which triggers the NEG creation. There is an event emitted for NEG creation and I can verify through `gcloud` that a NEG exists with 0 endpoints.

Are you still seeing this issue? If yes, please provide the GKE version, and possible the yamls you are using. Thanks!

**Comment by swetharepakula** [comment]
Closing this issue out for now. If the problem resurfaces please re-open the issue or consider opening a support ticket on GKE.
