### ISSUE TITLE
Annotate Ingress resource with FrontendConfig for L7ILB

### ISSUE THREAD

**Issue by ybelMekk** [kubernetes/ingress-gce#1936]
When setting up an regional ssl policy, its possible to refer an Internal loadbalancer Frontend to the ssl policy  in `console` or with `gcloud`.

When it comes to the ingress resource and  mainly ELB i can define a `FrontendConfig` and and annotate my ingress resource with this `FrontendConfig` pointing to a predefined ssl-policy

My question:

Is there any way to do this also for ILB (`kubernetes.io/ingress.class: "gce-internal`), tried to annotate ingress with `FrontendConfig` configured with a regional `ssl_policy`, no work, seems like `FrontendConfig` (`networking.gke.io/v1beta1.FrontendConfig`) annotation is ignored by the reconciler. I also seen that the Feature list https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-configuration for ILB and ELB dont include FrontendConfig for ILB. why, when ssl-policy is supported by ILB?

I do see this when i describe the ingress (gce.internal):
`Error syncing to GCP: error running load balancer syncing routine: loadbalancer dxpsj1-some-fake-laodbalancer-d9ms01b9 does not exist: SetSslPolicy() is not supported for regional Target Https Proxies`

Or i could be missing out her? 😄 

Thanks

Youssef

**Comment by swetharepakula** [comment]
When frontendconfig was first created, ILB did not support SSL-policy, which is why the GKE integration was limited to the ELB. ILB now has the feature, but we currently are not taking on new features for Ingress as the Gateway API is now 

However we are no longer taking adding new features to Ingress in favor of the Gateway API which does allow configuring the SSL policy for ILB (https://cloud.google.com/kubernetes-engine/docs/how-to/configure-gateway-resources#configure_ssl_policies)

**Comment by JangGyeongSik** [comment]
+1

Is it possible that because it is not supported in L7 ILB, it is also not supported in GKE Internal Ingress?
