### ISSUE TITLE
Unexpected Automatic Creation of Network Endpoint Groups (NEG) on GKE

### ISSUE THREAD

**Issue by marsaultj** [kubernetes/ingress-gce#2581]
We are experiencing an issue with our production environment on Google Kubernetes Engine (GKE) where Network Endpoint Group (NEG) resources are being automatically created for all our services deployed on our GKE cluster.

Adding the annotation `cloud.google.com/neg: '{"ingress":false}'` removes the NEG, but it is automatically recreated after 2 minutes by the neg-controller. The annotation is replaced by:

```
cloud.google.com/neg: '{"exposed_ports": ...}'
cloud.google.com/neg-status
```
We are using an external Network passthrough Load Balancer with an Istio ingress gateway, and we do not utilize NEGs.

This behavior is unexpected, especially since our test environment, which is built from the same deployment code, does not exhibit this phenomenon and no NEG resources are created automatically.

How can we explain this difference in behavior between two seemingly identical environments? Is there a way to completely disable the automatic creation of NEGs in GKE?

**Comment by swetharepakula** [comment]
This is due to the preparation of migration of the control plane for CSM : https://cloud.google.com/service-mesh/docs/managed-control-plane-overview#control-plane-migration.

The automatic NEG creation is slowly being rolled out to all CSM enabled clusters which is likely the reason the test cluster is not exhibiting the same behavior as your production cluster.

If you have any more questions please open a Google Support Ticket with the topic as CSM. They will better be able to answer specific questions about your clusters and the state of the migration.
