### ISSUE TITLE
Ingress tries to create SSL certificate from secret with illegal name

### ISSUE THREAD

**Issue by rgfunk** [kubernetes/ingress-gce#321]
With revision acbecb5671a06fe5582e3d5b80d1aa6d48347be8 the naming for SSL certificates created from secrets was changed to include the ingress-uid as a suffix (in namer.go). However, clusters with ingress resources created before kubernetes version 1.3 have an empty ingress-uid, as described here:

https://github.com/kubernetes/ingress-gce/blob/master/BETA_LIMITATIONS.md#changing-the-cluster-uid

This leads to an illegal name for the ssl certificate (ending in "--"). Setting the uid is not an option as this would require deleting all ingress resources, which is currently not possible. It would be great if the naming supported a fallback in case the ingress-uid is not set.

The creation of all other ingress resources works fine without having the ingress-uid set.

**Comment by prameshj** [comment]
The naming convention was k8s-ssl-{nameHash}--{clusterId}-{secretHash} which got changed to k8s-ssl-{nameHash}-{secretHash}--{clusterId} here https://github.com/kubernetes/ingress-gce/pull/200 to be consistent with naming of other resources. However other resources use the load balancer name as the suffix which is guaranteed to be non-empty. The other resource names can get truncated if they exceed 63 chars and it doesn't matter because there aren't multiple resources for a single ingress instance. We cannot do the same thing for certs since we now support multiple certs. We could go back to this scheme - k8s-ssl-{nameHash}--{clusterId}-{secretHash} to fix the issue. I will work on it.

**Comment by prameshj** [comment]
I'll work on a fix for this.
